### ISSUE TITLE
Show base pairs when zoomed in enough

### ISSUE THREAD

**Issue by cmdcolin** [cmdcolin/mafviewer#1]

**Comment by MolGen** [comment]
That's exactly the feature I would like to see.

**Comment by cmdcolin** [comment]
Cool :) I think it wouldn't be too hard to add that. Do you have it setup already on your own data? just curious

**Comment by cmdcolin** [comment]
This should be working now. Tagged as release 0.2.0

Thanks for the encouragement :)

**Comment by cmdcolin** [comment]
Feel free to re-open /comment if not working
