### ISSUE TITLE
Feature Request: Color Mismatches by bases

### ISSUE THREAD

**Issue by petersbr** [cmdcolin/mafviewer#13]
Hello, 

I'm currently exploring your tool while looking at alignments of various haplotypes within a species.  My request is to ask that a styling option to color mismatched bases according to the actual base content, i.e. highlight SNPs.  Green for A, Blue for C, Orange for G, Red for T, something like that, or be able to set custom colors.

Just a wish, thanks for the nice plugin!

**Comment by cmdcolin** [comment]
Glad that it is working for you! It was a fun plugin to make.

I think this request should be possible, I will look into it.

**Comment by cmdcolin** [comment]
I went and pushed a change, you can define colors for mismatches as you will

Check out this repo for example https://github.com/cmdcolin/mafviewer/blob/master/test/data/trackList.json#L42-L61

**Comment by cmdcolin** [comment]
Let me know if this helps I really appreciate the feature request!

**Comment by petersbr** [comment]
Thank you Colin!  I am grateful for the effort you've put in.  

I've tested it and for a minute I was confused as to what was going on because the 'SNPS' are being represented as the inverse of how they are usually shown.  Normally, the mismatching alignment base is colored by which base the non-reference alignment has at that position rather than by what the reference has, in this update.  That is how IGV shows them: e.g. 
![image](https://user-images.githubusercontent.com/19472233/39058178-bd86dec4-4480-11e8-9848-574842606543.png)

For example, in that way, more information is conveyed because you can see that when you have a 'C' at some position in human (the reference) that is different in bears (G) and cows (A), you can see that some lineages have the same patterns of variation,  This may be more work than its worth for you.  

On my end, I don't have a JBrowse screenshot for you yet since I am currently struggling with the best way to address the overlapping alignment issue talked about in #7 since i haven't really played with the MAF format before.  If I get there, a picture should be much clearer than all my text above.

Thanks again, this is already an information gain!

**Comment by petersbr** [comment]
Created a pull request to give it the SNP-style behavior.  Your code was wonderfully clear so the change was a super easy swap.

**Comment by cmdcolin** [comment]
I think this is now supported so close for now :)

**Comment by cmdcolin** [comment]
Thanks again for the idea and PR!
