### ISSUE TITLE
Error when adding as plugin to JBrowse 1.16

### ISSUE THREAD

**Issue by subwaystation** [cmdcolin/mafviewer#19]
I get the following error when I add this plugin into the `plugins` folder and add `"plugins": ["MAFViewer"]` into `jbrowse_conf.json`:

```
[heumos@wave jbrowse-1.16.9-release]$ ./setup.sh 
Gathering system information ...done.
NOTE: Legacy scripts wig-to-json.pl and bam-to-json.pl have been removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, please use JBrowse 1.12.3 or earlier.
Installing node.js dependencies and building with webpack ... failed.  See setup.log file for error messages.
setup cannot continue, aborting.

Gathering system information ...
============== System information ====
+ lsb_release -a
./setup.sh: line 73: lsb_release: command not found
+ uname -a
Linux wave 5.8.7-arch1-1 #1 SMP PREEMPT Sat, 05 Sep 2020 12:31:32 +0000 x86_64 GNU/Linux
+ sw_vers
./setup.sh: line 75: sw_vers: command not found
+ grep MemTotal /proc/meminfo
MemTotal:       16287356 kB
+ echo

+ echo


done.


NOTE: Legacy scripts wig-to-json.pl and bam-to-json.pl have been removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, please use JBrowse 1.12.3 or earlier.


Installing node.js dependencies and building with webpack ...
Node v12.11.1 installed at /home/heumos/.nvm/versions/node/v12.11.1/bin/node with npm 6.13.6
yarn install v1.22.5
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.75s.
yarn run v1.22.5
$ webpack
clean-webpack-plugin: /home/heumos/Downloads/jbrowse-1.16.9-release/dist has been removed.
jbrowse-glob-loader: building 205 JBrowse modules
jbrowse-glob-loader: adding plugin module RegexSequenceSearch/View/SearchSeqDialog
jbrowse-glob-loader: adding plugin module RegexSequenceSearch/Store/SeqFeature/RegexSearch
jbrowse-glob-loader: adding plugin module RegexSequenceSearch/main
jbrowse-glob-loader: adding plugin module NeatHTMLFeatures/View/Track/NeatFeatures
jbrowse-glob-loader: adding plugin module NeatHTMLFeatures/main
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/Track/NeatFeatures
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/FeatureGlyph/UnprocessedTranscript
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/FeatureGlyph/Segments
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/FeatureGlyph/ProcessedTranscript
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/FeatureGlyph/Gene
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/FeatureGlyph/Box
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/main
jbrowse-glob-loader: adding plugin module mafviewer/View/Track/MAF
jbrowse-glob-loader: adding plugin module mafviewer/View/FeatureGlyph/MAF
jbrowse-glob-loader: adding plugin module mafviewer/Store/SeqFeature/MAFTabix
jbrowse-glob-loader: adding plugin module mafviewer/Store/SeqFeature/MAF
jbrowse-glob-loader: adding plugin module mafviewer/Store/SeqFeature/BigMaf
jbrowse-glob-loader: adding plugin module mafviewer/main
jbrowse-glob-loader: adding plugin module HideTrackLabels/main
jbrowse-glob-loader: adding plugin module DebugEvents/main
jbrowse-glob-loader: adding plugin module CategoryUrl/main
jbrowse-glob-loader: discovered a total of 226 modules
jbrowse-glob-loader: skipping entry point module JBrowse/standalone
jbrowse-glob-loader: skipping entry point module JBrowse/main
jbrowse-glob-loader: skipping entry point module JBrowse/standalone
jbrowse-glob-loader: skipping entry point module JBrowse/main
Hash: 9d92b8c8dc237cfed3e8
Version: webpack 4.42.0
Time: 52456ms
Built at: 09/18/2020 11:41:44 AM
 6 assets
Entrypoint main = main.bundle.js
Entrypoint browser = browser.bundle.js
[130] ./src/JBrowse/Browser.js 146 KiB {1} [built]
[333] ./build/dojo-webpack-plugin-loader/dojo/dojo.js 70.1 KiB {2} {3} [built]
[334] ./src/JBrowse/Util.js 23.1 KiB {1} [built]
[335] ./src/JBrowse/QueryParamConfigMapper.js 5.99 KiB {1} [built]
[336] ./src/JBrowse/Model/XHRBlob.js 13.4 KiB {1} [built]
[337] ./src/JBrowse/Store/SeqFeature.js 13.5 KiB {1} [built]
[338] ./src/JBrowse/Model/SimpleFeature.js 2.81 KiB {1} [built]
[339] ./src/JBrowse/Store/DeferredFeaturesMixin.js 1.2 KiB {1} [built]
[340] ./src/JBrowse/Store/DeferredStatsMixin.js 1.65 KiB {1} [built]
[341] ./src/JBrowse/Errors.js 1.58 KiB {1} [built]
[342] ./src/JBrowse/has.js 1.3 KiB {1} [built]
[343] ./src/JBrowse/Model/FileBlob.js 5.45 KiB {1} [built]
[344] ./src/JBrowse/Model/Location.js 1.62 KiB {1} [built]
[558] ./src/JBrowse/main.js 12 KiB {3} [built]
[559] ./src/JBrowse/standalone.js 8.16 KiB {2} [built]
    + 1911 hidden modules

ERROR in ./plugins/mafviewer/js/Store/SeqFeature/MAF.js
Module not found: Error: Can't resolve 'MAFViewer/Store/SeqFeature/MAFTabix' in '/home/heumos/Downloads/jbrowse-1.16.9-release/plugins/mafviewer/js/Store/SeqFeature'
 @ ./plugins/mafviewer/js/Store/SeqFeature/MAF.js 1:0-3:2
 @ ./src/JBrowse/main.js
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Installing Perl prerequisites ...done.

Formatting Volvox example data ...done.
To see the volvox example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/volvox.

Formatting Yeast example data ...done.
To see the yeast example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/yeast.
```

**Comment by subwaystation** [comment]
Sorry for the rude opening. I am wondering if I am doing something wrong when adding the plugin to JBrowse. I followed https://jbrowse.org/docs/installation.html#alternative-jbrowse-setup-needed-if-you-use-plugins so far and then the issue appeared.

Generally, I am looking for a visualization tool that can visualize MAF Multiple Alignment Format. The only working tool I found is http://globin.bx.psu.edu/dist/gmaj/. But this plugin looks much nice and has more functionality. 
Any help to get this to run highly appreciated!

**Comment by cmdcolin** [comment]
No worries :+1: 

I think this is simply due to not having the folder named MAFViewer (instead it is named lower case mafviewer) I think.  This of course came from my weird insistence to give all my repositories lower case names....ohwell

I might be able to rename the files so that they use relative paths instead of the absolute name

Also note, if you need generic MAF viewer, there are limitations to this plugin namely that MAF features/chunks should be nonoverlapping

See the README
https://github.com/cmdcolin/mafviewer

**Comment by subwaystation** [comment]
Thanks for the feedback!

I also tried `"plugins": ["mafviewer"]`, but that wasn't the trick. 

You have to rename a bunch of files before it works?

Thanks for pointing that out. Currently, I assume that the MAF files I want to visualize won't have overlapping blocks.

**Comment by cmdcolin** [comment]
It should involve renaming the folder from plugins/mafviewer->plugins/MAFViewer, and then you don't even technically have to put MAFViewer in the plugins section in newer versions of jbrowse

**Comment by cmdcolin** [comment]
(post 1.13.0)

**Comment by subwaystation** [comment]
Great, now it was able to integrate it:

```
jbrowse-glob-loader: adding plugin module MAFViewer/View/Track/MAF
jbrowse-glob-loader: adding plugin module MAFViewer/View/FeatureGlyph/MAF
jbrowse-glob-loader: adding plugin module MAFViewer/Store/SeqFeature/MAFTabix
jbrowse-glob-loader: adding plugin module MAFViewer/Store/SeqFeature/MAF
jbrowse-glob-loader: adding plugin module MAFViewer/Store/SeqFeature/BigMaf
jbrowse-glob-loader: adding plugin module MAFViewer/main
```
Thanks!

I did `yarn watch` on my local machine, but how can I open JBrowse now in my browser? I did not finde somehting in the JBrowser Docs.

**Comment by subwaystation** [comment]
It says port `8082` but `localhost:8082` gives me a 404.

**Comment by cmdcolin** [comment]
In a different tab you can run `yarn start` which will bootup on 8082
https://github.com/gmod/jbrowse#develop-jbrowse-or-jbrowse-plugins

Some programs automatically start a web server and webpack with a single command but we generally have two

yarn watch in one terminal window, starts webpack watcher
yarn start in another terminal window, to start an express.js webserver, or, host the app on something like apache

**Comment by subwaystation** [comment]
Ah I thought it would watch and start. Thanks.

Now I got 
![image](https://user-images.githubusercontent.com/10184961/93609949-b5fb2080-f9cc-11ea-8cbc-0a33fe71b19d.png)

I assume this is because I did not add any data, yet?

**Comment by cmdcolin** [comment]
Ya that is the screen that is presented when no data is loaded

You can test a preloaded dataset by visiting

http://localhost:8082/?data=plugins/MAFViewer/test/data

I'm noticing some of the other demos (test/medaka and test/hg38) aren't loading as well so might be worth investigating, but the test/data one should would when zoomed in

**Comment by cmdcolin** [comment]
test/hg38 is just the data at the end of the chromosome and is loading fine actually

http://localhost:8082/?data=plugins%2FMAFViewer%2Ftest%2Fhg38&loc=chr21%3A5117246..5171940&tracks=MAF&highlight=


medaka should be ok too, except it works better zoomed in than zoomed far out...it sometimes erroneously goes into "feature density mode" which can be overriden in track configuration with maxFeatureScreenDensity: larger number

Could also use some optimizations potentially :)

**Comment by subwaystation** [comment]
Yes, if I zoom in, it works :+1: 

Thanks for the help! I will find out how to add my own MAF and be happy :)

**Comment by subwaystation** [comment]
Just FYI: I got it to run for some small example data. Took me some time to figure out, that some part of the data was not visualized, because of overlapping tracks. Which is what you warned me about. 
But a warning from JBrowse or so would have been helpful. As I do not know, which tracks are visualized, in the end.

**Comment by cmdcolin** [comment]
Gotcha. One way to help "check whether your data looks ok" is to make a track config like this

https://github.com/cmdcolin/mafviewer/blob/master/test/data/trackList.json#L80-L85

And this will make a track that just outputs box features for the span of each alignment in the MAF file, and then you would check whether those boxes are non-overlapping

Example for what it looks like for the sample data http://localhost/jbrowse/?data=plugins%2FMAFViewer%2Ftest%2Fdata&loc=chrI%3A3962635..3976691&tracks=MAF%20CF&highlight=

I don't really know how the UCSC pipeline works but it outputs nice nonoverlapping features. Handling overlapping would be interesting but sort of unclear how it could be incorporated smoothly into this
