### ISSUE TITLE
missing sequences in the visualization

### ISSUE THREAD

**Issue by AndreaGuarracino** [cmdcolin/mafviewer#20]
With this toy MAF file

```
##maf version=1
# maffer
# input=t.gfa

a loops=false
s hg38.chrY 0 13 + 64 CAAATAAG---CTTGG
s other.chrX 0 16 + 58 CAAATAAGGCTCTTGG

a loops=false
s hg38.chrY 39 12 - 64 AAATTTTCTGGA
s other.chrX 16 12 + 58 AAATTTTCTGGA

a loops=false
s hg38.chrY 25 7 + 64 GATTACA
s other.chrX 28 7 + 58 GATTACA

a loops=true
s hg38.chrY 44 9 + 64 ATATGCATC
s hg38.chrY 32 9 + 64 ATATGCATC
s other.chrX 14 9 - 58 ATATGCATC

a loops=false
s hg38.chrY 41 3 + 64 TCA
s other.chrX 44 3 + 58 TCA

a loops=false
s hg38.chrY 53 11 + 64 CCAACTCTCTG
s other.chrX 47 11 + 58 CCAACTCTCTG
```

I did

```
maf2bed.pl hg38 < hg38.chrY.maf > hg38.chrY.txt 
bedtools sort -i hg38.chrY.txt > hg38.chrY.sorted.txt
bgzip hg38.chrY.sorted.txt 
tabix -p bed hg38.chrY.sorted.txt.gz 
```

and created

`seq/refSeqs.json`
```
[{"length":100,"name":"hg38.chrY","end":100,"start":0}]
```

`trackList.json`
```
{
    "tracks": [
      {
        "label": "MAF",
        "urlTemplate": "hg38.chrY.sorted.txt.gz",
        "storeClass": "MAFViewer/Store/SeqFeature/MAFTabix",
        "type": "MAFViewer/View/Track/MAF",
        "samples": [
          "hg38",
          "other",
        ]
      }
    ]
  }
```

But I don't see any sequence

![image](https://user-images.githubusercontent.com/62253982/93922759-ab18f680-fd12-11ea-8a7d-d8392492f5d9.png)

Can you help me to find out my silly error?

**Comment by cmdcolin** [comment]
The reference genome that you load into jbrowse should just have fasta name

```
>chrY
ACGT....
```
It looks like the refname that got loaded was with the prefix

```
>hg38.chrY
ACGT...
```

The maf2bin strips the hg38 prefix in the resulting hg38.chrY.sorted.txt.gz  but needs it for all the other "species" subtracks

Good question :)

Note that your first line contains an insertion

a loops=false
s hg38.chrY 0 13 + 64 CAAATAAG---CTTGG
s other.chrX 0 16 + 58 CAAATAAGGCTCTTGG



Currently this plugin does not show insertions, it should probably do something similar to how we draw bam insertions e.g. just a little vertical bar or something

**Comment by AndreaGuarracino** [comment]
Thank you @cmdcolin, now it works!

Regarding the insertions, is this the visualization you would expect from such a toy MAF file then? 

![image](https://user-images.githubusercontent.com/62253982/93940965-c5140280-fd2d-11ea-8f98-0e2a5aa2fd59.png)

**Comment by cmdcolin** [comment]
Looks right to me!

**Comment by AndreaGuarracino** [comment]
Great! You were very quick and kind, thank you.
