### ISSUE TITLE
How to install in JBrowse 2 desktop app? 

### ISSUE THREAD

**Issue by thuynnguyen** [cmdcolin/mafviewer#23]
Hi there, 

Does the mafviewer plugin work for JBrowse 2 Desktop app? If so, how do I install it? It does not appear to be available in the "plugin store". 

Thank you,
Thuy

**Comment by cmdcolin** [comment]
Hi there, unfortunately, none of the jbrowse 1 plugins work in jbrowse 2, but I will take this as a note of interest that mafviewer would be a good candidate to port to jbrowse 2!

**Comment by bcantarel** [comment]
I would also like to use MAFViewer for JBrowse2!

**Comment by jdamas13** [comment]
+1 that would be a great tool for comparative genomics analyses.

**Comment by JAMKuttan** [comment]
I have been looking for exactly this! show my alignments!!!

**Comment by cmdcolin** [comment]
great to hear! I'll add a note to this thread if there are any updates about getting this into jbrowse 2 :)

**Comment by biouserPD** [comment]
Hi there,
do you have any news about the porting of the mafviewer into the jbrowse2 desktop?
Thanks a lot

**Comment by cmdcolin** [comment]
no updates yet, but will keep you posted @biouserPD

**Comment by gremory-x** [comment]
Same need, are there any tools alternative?

**Comment by cmdcolin** [comment]
Thanks again for the interest. I should try and make a update to this for jbrowse2 . I have a lot on my plate but I bet I can make a "1-for-1" copy as a jbrowse 2 plugin without too much delay. I will try to post an update...within a week let's say!

**Comment by cmdcolin** [comment]
as promised, an update! 

I created a jbrowse 2 version of mafviewer here! https://github.com/cmdcolin/jbrowse-plugin-mafviewer
I think it's basically matching the functionality from this plugin

 live demo showing it working https://jbrowse.org/code/jb2/re-export-more/?config=%2Fdemos%2Fmafviewer%2Fhg38%2Fconfig.json&session=share-O3sxhB3iS2&password=8Ysiv


screenshot

![image](https://github.com/cmdcolin/mafviewer/assets/6511937/5242cd7a-c246-4235-9b5f-5b5ae8d2712c)

**Comment by cmdcolin** [comment]
it is now available in the plugin store. there are now install instructions for usage in jbrowse desktop and manual config editing here https://github.com/cmdcolin/jbrowse-plugin-mafviewer#gui-usage-eg-in-jbrowse-desktop

**Comment by cmdcolin** [comment]
really appreciate everyone expressing their support for this plugin here, and let me know if you have any questions. more features like mouseover and ui improvements are not yet there, but can be added over time...can  open new issues in https://github.com/cmdcolin/jbrowse-plugin-mafviewer also for more requests!

**Comment by cmdcolin** [comment]
random add on content: tried making a speed up script for preparing maftabix using rust https://github.com/cmdcolin/maf2bed. was able to process the entire https://hgdownload.soe.ucsc.edu/goldenPath/hg38/multiz30way/maf/ directory in 10 minutes (about 7x faster than perl maf2bed.pl)

**Comment by thuynnguyen** [comment]
Thank you @cmdcolin for following through!! 🥳

**Comment by cmdcolin** [comment]
happy to do so! do let me know if you have any bugs or feature requests
