### ISSUE TITLE
mafviewer & JBrowseDesktop.app

### ISSUE THREAD

**Issue by chlangley** [cmdcolin/mafviewer#9]
Hello:

This is not really an 'issue'.  More just a lazy nub asking to handholding.

We want to test out mafviewer before launching into a website, etc.

But we have not been able to get the plugin loaded in JBrowseDesktop.app (macosx).

Is mafviewer designed to work with the app or do we have to immediate go to the web version of JBrowse?

Thanks for any advise 

Cheers,
Chuck

**Comment by cmdcolin** [comment]
Good question. Technically it should work fine with the desktop version but the config is a little advanced so it might require hand editing the config files and running the preprocessing script for maf2bed. Did you get the maf to bed script to run yet?

Glad to hear interest in the plug-in !

**Comment by chlangley** [comment]
> On 15/Aug/2017, at 4:23 PM, Colin Diesh <notifications@github.com> wrote:
> 
> Did you get the maf to bed script to run yet?


Yes I believe that maf2bed script works here.  Right, Kristian?

Cheers,
Chuck

**Comment by chlangley** [comment]
plugin loaded by cloning the GitHub and then renaming the mafviewer directory to MAFViewer. not sure if this is the way, but I wanted to make sure the name matched with the config.

delta files successfully processed with delta2maf 

a prefix needed to be added (e.g. hg18) then

> maf2bed.pl

> bgzip

> tabix

all seemingly fine.

but loading the .gz produces no visible results. even after type changed to "type": "MAFViewer/View/Track/MAF”, in config.

**Comment by cmdcolin** [comment]
The key might be adding "samples". For the 100 genome alignment you can seee it's like https://github.com/cmdcolin/mafviewer/blob/master/test/hg38/trackList.json but for yours if it's just pairwise, it would probably just be the prefix that you added to the other species in the MAF file. If you have a small sample of the outputted bed file (gunzip -c file.bed.gz | head) that could possibly help too.

**Comment by chlangley** [comment]
Thanks.

We'll investigate and get back.

Cheers,
Chuck

**Comment by chlangley** [comment]
Attached are config and two lines the maf.txt.gz file. It displays fine as uncompressed bed, but not as MAF 

{
  "label": "MAF",
  "urlTemplate": "hinds_chandler.scaffold943.maf.txt.gz",
  "storeClass": "MAFViewer/Store/SeqFeature/MAF",
  "type": "MAFViewer/View/Track/MAF",
  "samples": [
    “foo"
  ]
}

scaffold943	14306	14768	foo_9	1	foo.scaffold943:14306:462:+:776835:gagcgagaagtctcaaacagaggggatcgagtaccggcttgctgtggtgggaatttggtagaagaattaagtggccatttccaagtgttgtag---cttcagagatcgcctggcctgtttaaatagacatgagttgcgtgcgtcaccgtgtggatcgatcagtcagtgtggaccatagagcaagaaaacgatctcttagcttttagctggccggacagtagtgttattaatttgcac--gca---tg--------catcttacgtgtccacgttttcttttttgaggg-gtatggattaagaaatacttccatgaaaaataatgatacagccacgccacgtcacgtcgatagatacgtatataaataacatttactttttttatttttaatgagtaaataatatctcttgatcagtt-cttgtaa----tcgtttgtttgttttctttaccaacttaataataccacgtgcaactttattaaaa,super511:148055:468:+:273470:gagcgagaagtctcaaacagaggggatcgagtaccgacttgctgtgttgggaatttggcaaaagaattaagtggccatttccgagtgttgtagcttcttcagagagcgc----cctatttaaatagacatgagttgcgtgcgtcaccatgtgg-------agtcagtgtggaccatacagcaagaaaatgatctcttagcttttagctggccggacagtagtgttattaatttgcacgtgcaatttgtatccatacatcttacatgtccacgttttcttttttgagggggtatggattaagaaatacttacatgaaaaataatgatacagtcacgc-----cacgtcgatagatacgtatgtaaataacatttactttttttatttttaatgagtaaataatatctcttgatcagttccatataattgtttgtttgtttgttttctttactaacttaataataccacgtgcaactttattaaaa
scaffold943	14840	15304	foo_10	1	foo.scaffold943:14840:464:+:776835:tttctttaccaacttaataataccacgtgcaactttattaaaaaaaattaataaacagaactttaaggccggcaaggcggcctccttgttgtcaaatcaacaattgtcttaaaaaattaaacggaaagagtaagtttaataatttatttgtcttaatatttaattaaggccgtgtttgattgcgagatttagatgaattcagtctaattttaagttaaatttaatatttaaatattaaactctcaaattattaaactcatctcaattcaaaacctccttatacgtaagacttacaatattttttaacttaacacatctttatacatgagacctacaacttttttcaacttctcataaaaagtattaaactcatattaacatccaaacacactttaaactcaatttagatagatccagcataactctctctactactcaactcattactattcataaagaactga,super511:151170:455:+:273470:tttctttactaacttaataataccacgtgcaactttattaaaataaattaataaacagaactttaaggccggcaaggcagcctccttgttgtcaaatcaacaattgtctttaaaaattaaacggaaagagtaagtttaataatttatttgtcttaatatttaattaagtttacgtttggttac-a-at---gtt--cctcaatctaattttaagttaaatttaatatctaaatattaagttttcaaattattaaactcatctcaactcaaaatttctttacacgtgagatctataatattttttaacctaacacatttgtatacgtaagactcgtaacttttttcaacttcatataaaaagtgttaaacttatcttaacatctaaatacactttaaactca—ttagataggtccaatataactccctctattactcaactcattactattcataaataactga


> On Aug 16, 2017, at 7:47 AM, Charles Langley <chlangley@ucdavis.edu> wrote:
> 
>> The key might be adding "samples". For the 100 genome alignment you can seee it's like https://github.com/cmdcolin/mafviewer/blob/master/test/hg38/trackList.json but for yours if it's just pairwise, it would probably just be the prefix that you added to the other species in the MAF file. If you have a small sample of the outputted bed file (gunzip -c file.bed.gz | head) that could possibly help too.
>> 

Kristian Stevens Ph.D.

Principal Bioinformatician
3206 Storer Hall
Dept. of Evolution & Ecology
Foundation Plant Services
University of California Davis
One Shields Avenue,
Davis, CA  95616

**Comment by cmdcolin** [comment]
This config basically looks fine to me. You might want to say "super511" in samples instead of foo there since "foo" is the reference, and "super511" is the sample you are comparing to. Actually you can have both "foo" and "super511" in samples, but "foo" will just be a solid green bar

I made a tiny example data directory that works with this even just single line of data, and it seems to display ok for me

Example


![screenshot-localhost-2017-08-18-08-55-38](https://user-images.githubusercontent.com/6511937/29459747-279ab398-83f3-11e7-80c2-8ccf0d17ba63.png)

The config you used looks essentially fine otherwise. Can you check the javascript console to see if there are any errors? If for example, when you turn on the track, nothing happens at all, that probably means there is a problem with the plugin not being declared or something of this nature and the javascript console will have the error.

Here is the config I used

[test_maf.tar.gz](https://github.com/cmdcolin/mafviewer/files/1234468/test_maf.tar.gz)

**Comment by chlangley** [comment]
Hello Colin:


It does seem to be that the plugin is not install/functional.

What best approach to sorting this out ?

Thanks for any help.

Cheers,
Chuck

**Comment by cmdcolin** [comment]
It's a little tricky to debug the problem. If you want I can try to schedule a video conference or something! I am currently on break so fairly open

**Comment by chlangley** [comment]
> On 21/Aug/2017, at 9:35 AM, Colin Diesh <notifications@github.com> wrote:
> 
> It's a little tricky to debug the problem. If you want I can try to schedule a video conference or something! I am currently on break so fairly open

OK.  

But before we dive into this I am interested in your view.  Is this likely to be Desktop JBrowse specific?

And is there a light-weight web-server installation that is appropriate for introductory exploration?

We could skype/facetime anytime in next 4 hours.

Cheers,
Chuck

PS:  How was the eclipse there?

**Comment by cmdcolin** [comment]
Does google hangouts work? I could maybe meet shortly

**Comment by chlangley** [comment]
we’ll let you know as soon as we get ‘hang out’ working.

**Comment by chlangley** [comment]
what’s your id?

**Comment by cmdcolin** [comment]
It's colin.diesh@gmail.com

**Comment by chlangley** [comment]
we calling as kristian.stevens@gmail.com

**Comment by cmdcolin** [comment]
Glad this was sort of resolved. Let me know if you have any more issues!

**Comment by chlangley** [comment]
Thanks for the help.
You'll hear from us soon.
Thanks again.
Chuck & Kristian
